# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1034, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.paths_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paths_groupBox.sizePolicy().hasHeightForWidth())
        self.paths_groupBox.setSizePolicy(sizePolicy)
        self.paths_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.paths_groupBox.setObjectName("paths_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.paths_groupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.syncPath_lineEdit = QtWidgets.QLineEdit(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncPath_lineEdit.sizePolicy().hasHeightForWidth())
        self.syncPath_lineEdit.setSizePolicy(sizePolicy)
        self.syncPath_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.syncPath_lineEdit.setObjectName("syncPath_lineEdit")
        self.gridLayout.addWidget(self.syncPath_lineEdit, 1, 1, 1, 1)
        self.loadSyncPath_pushButton = QtWidgets.QPushButton(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadSyncPath_pushButton.sizePolicy().hasHeightForWidth())
        self.loadSyncPath_pushButton.setSizePolicy(sizePolicy)
        self.loadSyncPath_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadSyncPath_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.loadSyncPath_pushButton.setObjectName("loadSyncPath_pushButton")
        self.gridLayout.addWidget(self.loadSyncPath_pushButton, 1, 2, 1, 1)
        self.moviePath_lineEdit = QtWidgets.QLineEdit(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moviePath_lineEdit.sizePolicy().hasHeightForWidth())
        self.moviePath_lineEdit.setSizePolicy(sizePolicy)
        self.moviePath_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.moviePath_lineEdit.setObjectName("moviePath_lineEdit")
        self.gridLayout.addWidget(self.moviePath_lineEdit, 0, 1, 1, 1)
        self.loadStimOrderPath_pushButton = QtWidgets.QPushButton(self.paths_groupBox)
        self.loadStimOrderPath_pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadStimOrderPath_pushButton.sizePolicy().hasHeightForWidth())
        self.loadStimOrderPath_pushButton.setSizePolicy(sizePolicy)
        self.loadStimOrderPath_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadStimOrderPath_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.loadStimOrderPath_pushButton.setObjectName("loadStimOrderPath_pushButton")
        self.gridLayout.addWidget(self.loadStimOrderPath_pushButton, 2, 2, 1, 1)
        self.savePath_lineEdit = QtWidgets.QLineEdit(self.paths_groupBox)
        self.savePath_lineEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.savePath_lineEdit.sizePolicy().hasHeightForWidth())
        self.savePath_lineEdit.setSizePolicy(sizePolicy)
        self.savePath_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.savePath_lineEdit.setObjectName("savePath_lineEdit")
        self.gridLayout.addWidget(self.savePath_lineEdit, 3, 1, 1, 1)
        self.useStimOrder_checkBox = QtWidgets.QCheckBox(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useStimOrder_checkBox.sizePolicy().hasHeightForWidth())
        self.useStimOrder_checkBox.setSizePolicy(sizePolicy)
        self.useStimOrder_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.useStimOrder_checkBox.setObjectName("useStimOrder_checkBox")
        self.gridLayout.addWidget(self.useStimOrder_checkBox, 2, 0, 1, 1)
        self.setSavePath_pushButton = QtWidgets.QPushButton(self.paths_groupBox)
        self.setSavePath_pushButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setSavePath_pushButton.sizePolicy().hasHeightForWidth())
        self.setSavePath_pushButton.setSizePolicy(sizePolicy)
        self.setSavePath_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.setSavePath_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.setSavePath_pushButton.setObjectName("setSavePath_pushButton")
        self.gridLayout.addWidget(self.setSavePath_pushButton, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.paths_groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(0, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.stimOrder_lineEdit = QtWidgets.QLineEdit(self.paths_groupBox)
        self.stimOrder_lineEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stimOrder_lineEdit.sizePolicy().hasHeightForWidth())
        self.stimOrder_lineEdit.setSizePolicy(sizePolicy)
        self.stimOrder_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.stimOrder_lineEdit.setObjectName("stimOrder_lineEdit")
        self.gridLayout.addWidget(self.stimOrder_lineEdit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.loadMoviePath_pushButton = QtWidgets.QPushButton(self.paths_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadMoviePath_pushButton.sizePolicy().hasHeightForWidth())
        self.loadMoviePath_pushButton.setSizePolicy(sizePolicy)
        self.loadMoviePath_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadMoviePath_pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.loadMoviePath_pushButton.setObjectName("loadMoviePath_pushButton")
        self.gridLayout.addWidget(self.loadMoviePath_pushButton, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_6.addWidget(self.paths_groupBox, 0, 0, 1, 1)
        self.presets_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.presets_groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.presets_groupBox.setObjectName("presets_groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.presets_groupBox)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.setDefaults_pushButton = QtWidgets.QPushButton(self.presets_groupBox)
        self.setDefaults_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.setDefaults_pushButton.setObjectName("setDefaults_pushButton")
        self.gridLayout_7.addWidget(self.setDefaults_pushButton, 0, 2, 1, 1)
        self.loadPreset_pushButton = QtWidgets.QPushButton(self.presets_groupBox)
        self.loadPreset_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.loadPreset_pushButton.setObjectName("loadPreset_pushButton")
        self.gridLayout_7.addWidget(self.loadPreset_pushButton, 0, 0, 1, 1)
        self.savePreset_pushButton = QtWidgets.QPushButton(self.presets_groupBox)
        self.savePreset_pushButton.setMinimumSize(QtCore.QSize(0, 20))
        self.savePreset_pushButton.setObjectName("savePreset_pushButton")
        self.gridLayout_7.addWidget(self.savePreset_pushButton, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_7)
        self.loadedPreset_label = QtWidgets.QLabel(self.presets_groupBox)
        self.loadedPreset_label.setMinimumSize(QtCore.QSize(0, 20))
        self.loadedPreset_label.setAlignment(QtCore.Qt.AlignCenter)
        self.loadedPreset_label.setObjectName("loadedPreset_label")
        self.verticalLayout_2.addWidget(self.loadedPreset_label)
        self.gridLayout_6.addWidget(self.presets_groupBox, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_6)
        self.settings_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings_groupBox.sizePolicy().hasHeightForWidth())
        self.settings_groupBox.setSizePolicy(sizePolicy)
        self.settings_groupBox.setAutoFillBackground(False)
        self.settings_groupBox.setFlat(False)
        self.settings_groupBox.setObjectName("settings_groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.settings_groupBox)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(-1, 0, 0, -1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_9.addWidget(self.label_6, 0, 0, 1, 1)
        self.numDiffStims_spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numDiffStims_spinBox.sizePolicy().hasHeightForWidth())
        self.numDiffStims_spinBox.setSizePolicy(sizePolicy)
        self.numDiffStims_spinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.numDiffStims_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.numDiffStims_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.numDiffStims_spinBox.setMinimum(1)
        self.numDiffStims_spinBox.setMaximum(9999)
        self.numDiffStims_spinBox.setObjectName("numDiffStims_spinBox")
        self.gridLayout_9.addWidget(self.numDiffStims_spinBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(0, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_9.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 2, 0, 1, 1)
        self.everyXStims_spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.everyXStims_spinBox.sizePolicy().hasHeightForWidth())
        self.everyXStims_spinBox.setSizePolicy(sizePolicy)
        self.everyXStims_spinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.everyXStims_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.everyXStims_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.everyXStims_spinBox.setMinimum(1)
        self.everyXStims_spinBox.setMaximum(9999)
        self.everyXStims_spinBox.setObjectName("everyXStims_spinBox")
        self.gridLayout_9.addWidget(self.everyXStims_spinBox, 1, 1, 1, 1)
        self.startOnStim_spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startOnStim_spinBox.sizePolicy().hasHeightForWidth())
        self.startOnStim_spinBox.setSizePolicy(sizePolicy)
        self.startOnStim_spinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.startOnStim_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.startOnStim_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.startOnStim_spinBox.setMinimum(1)
        self.startOnStim_spinBox.setMaximum(9999)
        self.startOnStim_spinBox.setObjectName("startOnStim_spinBox")
        self.gridLayout_9.addWidget(self.startOnStim_spinBox, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox1 = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(sizePolicy)
        self.groupBox1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.syncFrameChannel_lineEdit = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncFrameChannel_lineEdit.sizePolicy().hasHeightForWidth())
        self.syncFrameChannel_lineEdit.setSizePolicy(sizePolicy)
        self.syncFrameChannel_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.syncFrameChannel_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.syncFrameChannel_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.syncFrameChannel_lineEdit.setObjectName("syncFrameChannel_lineEdit")
        self.gridLayout_10.addWidget(self.syncFrameChannel_lineEdit, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_10.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 2, 0, 1, 1)
        self.syncStimChannel_lineEdit = QtWidgets.QLineEdit(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncStimChannel_lineEdit.sizePolicy().hasHeightForWidth())
        self.syncStimChannel_lineEdit.setSizePolicy(sizePolicy)
        self.syncStimChannel_lineEdit.setMinimumSize(QtCore.QSize(0, 20))
        self.syncStimChannel_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.syncStimChannel_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.syncStimChannel_lineEdit.setObjectName("syncStimChannel_lineEdit")
        self.gridLayout_10.addWidget(self.syncStimChannel_lineEdit, 1, 1, 1, 1)
        self.syncStartSec_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncStartSec_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.syncStartSec_doubleSpinBox.setSizePolicy(sizePolicy)
        self.syncStartSec_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.syncStartSec_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.syncStartSec_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.syncStartSec_doubleSpinBox.setPrefix("")
        self.syncStartSec_doubleSpinBox.setDecimals(3)
        self.syncStartSec_doubleSpinBox.setMaximum(9999.0)
        self.syncStartSec_doubleSpinBox.setObjectName("syncStartSec_doubleSpinBox")
        self.gridLayout_10.addWidget(self.syncStartSec_doubleSpinBox, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_10.addWidget(self.label_10, 1, 0, 1, 1)
        self.syncStopSec_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syncStopSec_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.syncStopSec_doubleSpinBox.setSizePolicy(sizePolicy)
        self.syncStopSec_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.syncStopSec_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.syncStopSec_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.syncStopSec_doubleSpinBox.setPrefix("")
        self.syncStopSec_doubleSpinBox.setDecimals(3)
        self.syncStopSec_doubleSpinBox.setMinimum(0.0)
        self.syncStopSec_doubleSpinBox.setMaximum(9999.0)
        self.syncStopSec_doubleSpinBox.setObjectName("syncStopSec_doubleSpinBox")
        self.gridLayout_10.addWidget(self.syncStopSec_doubleSpinBox, 3, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox1)
        self.groupBox2 = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox2.sizePolicy().hasHeightForWidth())
        self.groupBox2.setSizePolicy(sizePolicy)
        self.groupBox2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox2.setObjectName("groupBox2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox2)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frameRate_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameRate_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.frameRate_doubleSpinBox.setSizePolicy(sizePolicy)
        self.frameRate_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.frameRate_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.frameRate_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.frameRate_doubleSpinBox.setPrefix("")
        self.frameRate_doubleSpinBox.setDecimals(3)
        self.frameRate_doubleSpinBox.setMaximum(1000.0)
        self.frameRate_doubleSpinBox.setObjectName("frameRate_doubleSpinBox")
        self.gridLayout_2.addWidget(self.frameRate_doubleSpinBox, 2, 1, 1, 1)
        self.preSeconds_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preSeconds_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.preSeconds_doubleSpinBox.setSizePolicy(sizePolicy)
        self.preSeconds_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.preSeconds_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.preSeconds_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.preSeconds_doubleSpinBox.setPrefix("")
        self.preSeconds_doubleSpinBox.setDecimals(3)
        self.preSeconds_doubleSpinBox.setObjectName("preSeconds_doubleSpinBox")
        self.gridLayout_2.addWidget(self.preSeconds_doubleSpinBox, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.postSeconds_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postSeconds_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.postSeconds_doubleSpinBox.setSizePolicy(sizePolicy)
        self.postSeconds_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.postSeconds_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.postSeconds_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.postSeconds_doubleSpinBox.setPrefix("")
        self.postSeconds_doubleSpinBox.setDecimals(3)
        self.postSeconds_doubleSpinBox.setObjectName("postSeconds_doubleSpinBox")
        self.gridLayout_2.addWidget(self.postSeconds_doubleSpinBox, 1, 1, 1, 1)
        self.zPlanes_spinBox = QtWidgets.QSpinBox(self.groupBox2)
        self.zPlanes_spinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.zPlanes_spinBox.setFrame(True)
        self.zPlanes_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.zPlanes_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.zPlanes_spinBox.setObjectName("zPlanes_spinBox")
        self.gridLayout_2.addWidget(self.zPlanes_spinBox, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.horizontalLayout_2.addWidget(self.groupBox2)
        self.groupBox3 = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox3.sizePolicy().hasHeightForWidth())
        self.groupBox3.setSizePolicy(sizePolicy)
        self.groupBox3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox3.setObjectName("groupBox3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox3)
        self.verticalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.averageImageStop_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageImageStop_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.averageImageStop_doubleSpinBox.setSizePolicy(sizePolicy)
        self.averageImageStop_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.averageImageStop_doubleSpinBox.setStatusTip("")
        self.averageImageStop_doubleSpinBox.setWrapping(False)
        self.averageImageStop_doubleSpinBox.setFrame(True)
        self.averageImageStop_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.averageImageStop_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.averageImageStop_doubleSpinBox.setAccelerated(False)
        self.averageImageStop_doubleSpinBox.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToPreviousValue)
        self.averageImageStop_doubleSpinBox.setKeyboardTracking(True)
        self.averageImageStop_doubleSpinBox.setProperty("showGroupSeparator", False)
        self.averageImageStop_doubleSpinBox.setPrefix("")
        self.averageImageStop_doubleSpinBox.setDecimals(3)
        self.averageImageStop_doubleSpinBox.setMinimum(-99.99)
        self.averageImageStop_doubleSpinBox.setObjectName("averageImageStop_doubleSpinBox")
        self.gridLayout_4.addWidget(self.averageImageStop_doubleSpinBox, 1, 1, 1, 1)
        self.averageImageStart_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.averageImageStart_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.averageImageStart_doubleSpinBox.setSizePolicy(sizePolicy)
        self.averageImageStart_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.averageImageStart_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.averageImageStart_doubleSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.averageImageStart_doubleSpinBox.setPrefix("")
        self.averageImageStart_doubleSpinBox.setDecimals(3)
        self.averageImageStart_doubleSpinBox.setMinimum(-99.99)
        self.averageImageStart_doubleSpinBox.setObjectName("averageImageStart_doubleSpinBox")
        self.gridLayout_4.addWidget(self.averageImageStart_doubleSpinBox, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.colourByTime_checkBox = QtWidgets.QCheckBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colourByTime_checkBox.sizePolicy().hasHeightForWidth())
        self.colourByTime_checkBox.setSizePolicy(sizePolicy)
        self.colourByTime_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.colourByTime_checkBox.setObjectName("colourByTime_checkBox")
        self.verticalLayout_8.addWidget(self.colourByTime_checkBox)
        self.useSingleTrials_checkBox = QtWidgets.QCheckBox(self.groupBox3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.useSingleTrials_checkBox.sizePolicy().hasHeightForWidth())
        self.useSingleTrials_checkBox.setSizePolicy(sizePolicy)
        self.useSingleTrials_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.useSingleTrials_checkBox.setObjectName("useSingleTrials_checkBox")
        self.verticalLayout_8.addWidget(self.useSingleTrials_checkBox)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_2.addWidget(self.groupBox3)
        self.groupBox4 = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox4.sizePolicy().hasHeightForWidth())
        self.groupBox4.setSizePolicy(sizePolicy)
        self.groupBox4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox4.setObjectName("groupBox4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox4)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.methodRaw_checkBox = QtWidgets.QCheckBox(self.groupBox4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodRaw_checkBox.sizePolicy().hasHeightForWidth())
        self.methodRaw_checkBox.setSizePolicy(sizePolicy)
        self.methodRaw_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.methodRaw_checkBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.methodRaw_checkBox.setObjectName("methodRaw_checkBox")
        self.gridLayout_11.addWidget(self.methodRaw_checkBox, 0, 0, 1, 1)
        self.methodDF_checkBox = QtWidgets.QCheckBox(self.groupBox4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodDF_checkBox.sizePolicy().hasHeightForWidth())
        self.methodDF_checkBox.setSizePolicy(sizePolicy)
        self.methodDF_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.methodDF_checkBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.methodDF_checkBox.setObjectName("methodDF_checkBox")
        self.gridLayout_11.addWidget(self.methodDF_checkBox, 1, 0, 1, 1)
        self.methodZscore_checkBox = QtWidgets.QCheckBox(self.groupBox4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodZscore_checkBox.sizePolicy().hasHeightForWidth())
        self.methodZscore_checkBox.setSizePolicy(sizePolicy)
        self.methodZscore_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.methodZscore_checkBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.methodZscore_checkBox.setObjectName("methodZscore_checkBox")
        self.gridLayout_11.addWidget(self.methodZscore_checkBox, 3, 0, 1, 1)
        self.methodDFF_checkBox = QtWidgets.QCheckBox(self.groupBox4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.methodDFF_checkBox.sizePolicy().hasHeightForWidth())
        self.methodDFF_checkBox.setSizePolicy(sizePolicy)
        self.methodDFF_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.methodDFF_checkBox.setMaximumSize(QtCore.QSize(80, 16777215))
        self.methodDFF_checkBox.setObjectName("methodDFF_checkBox")
        self.gridLayout_11.addWidget(self.methodDFF_checkBox, 2, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_2.addWidget(self.groupBox4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridGroupBox = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridGroupBox.sizePolicy().hasHeightForWidth())
        self.gridGroupBox.setSizePolicy(sizePolicy)
        self.gridGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.gridGroupBox)
        self.verticalLayout_10.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.doThreshold_checkBox = QtWidgets.QCheckBox(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doThreshold_checkBox.sizePolicy().hasHeightForWidth())
        self.doThreshold_checkBox.setSizePolicy(sizePolicy)
        self.doThreshold_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.doThreshold_checkBox.setObjectName("doThreshold_checkBox")
        self.horizontalLayout_5.addWidget(self.doThreshold_checkBox)
        self.threshold_doubleSpinBox = QtWidgets.QDoubleSpinBox(self.gridGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.threshold_doubleSpinBox.sizePolicy().hasHeightForWidth())
        self.threshold_doubleSpinBox.setSizePolicy(sizePolicy)
        self.threshold_doubleSpinBox.setMinimumSize(QtCore.QSize(0, 20))
        self.threshold_doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.threshold_doubleSpinBox.setObjectName("threshold_doubleSpinBox")
        self.horizontalLayout_5.addWidget(self.threshold_doubleSpinBox)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem5, 3, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.horizontalLayout_3.addWidget(self.gridGroupBox)
        self.groupBox5 = QtWidgets.QGroupBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox5.sizePolicy().hasHeightForWidth())
        self.groupBox5.setSizePolicy(sizePolicy)
        self.groupBox5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox5.setObjectName("groupBox5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox5)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.makeColourImage_checkBox = QtWidgets.QCheckBox(self.groupBox5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeColourImage_checkBox.sizePolicy().hasHeightForWidth())
        self.makeColourImage_checkBox.setSizePolicy(sizePolicy)
        self.makeColourImage_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.makeColourImage_checkBox.setChecked(True)
        self.makeColourImage_checkBox.setObjectName("makeColourImage_checkBox")
        self.gridLayout_5.addWidget(self.makeColourImage_checkBox, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem6, 4, 0, 1, 1)
        self.makeMaxImage_checkBox = QtWidgets.QCheckBox(self.groupBox5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.makeMaxImage_checkBox.sizePolicy().hasHeightForWidth())
        self.makeMaxImage_checkBox.setSizePolicy(sizePolicy)
        self.makeMaxImage_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.makeMaxImage_checkBox.setChecked(True)
        self.makeMaxImage_checkBox.setObjectName("makeMaxImage_checkBox")
        self.gridLayout_5.addWidget(self.makeMaxImage_checkBox, 1, 0, 1, 1)
        self.useCorrelationImage_checkBox = QtWidgets.QCheckBox(self.groupBox5)
        self.useCorrelationImage_checkBox.setObjectName("useCorrelationImage_checkBox")
        self.gridLayout_5.addWidget(self.useCorrelationImage_checkBox, 2, 0, 1, 1)
        self.blurHandS_checkBox = QtWidgets.QCheckBox(self.groupBox5)
        self.blurHandS_checkBox.setObjectName("blurHandS_checkBox")
        self.gridLayout_5.addWidget(self.blurHandS_checkBox, 3, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.horizontalLayout_3.addWidget(self.groupBox5)
        self.groupBox_2 = QtWidgets.QGroupBox(self.settings_groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.doMotionCorrection_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.doMotionCorrection_checkBox.setObjectName("doMotionCorrection_checkBox")
        self.verticalLayout_12.addWidget(self.doMotionCorrection_checkBox)
        self.useCUDA_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.useCUDA_checkBox.setObjectName("useCUDA_checkBox")
        self.verticalLayout_12.addWidget(self.useCUDA_checkBox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem7)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.run_pushButton = QtWidgets.QPushButton(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.run_pushButton.sizePolicy().hasHeightForWidth())
        self.run_pushButton.setSizePolicy(sizePolicy)
        self.run_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        self.run_pushButton.setObjectName("run_pushButton")
        self.gridLayout_8.addWidget(self.run_pushButton, 1, 1, 1, 1)
        self.openResultsDir_checkBox = QtWidgets.QCheckBox(self.settings_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openResultsDir_checkBox.sizePolicy().hasHeightForWidth())
        self.openResultsDir_checkBox.setSizePolicy(sizePolicy)
        self.openResultsDir_checkBox.setMinimumSize(QtCore.QSize(0, 20))
        self.openResultsDir_checkBox.setChecked(True)
        self.openResultsDir_checkBox.setObjectName("openResultsDir_checkBox")
        self.gridLayout_8.addWidget(self.openResultsDir_checkBox, 2, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 0, 1, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addWidget(self.settings_groupBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1034, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.useStimOrder_checkBox.toggled['bool'].connect(self.stimOrder_lineEdit.setEnabled)
        self.useStimOrder_checkBox.toggled['bool'].connect(self.loadStimOrderPath_pushButton.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.moviePath_lineEdit, self.loadMoviePath_pushButton)
        MainWindow.setTabOrder(self.loadMoviePath_pushButton, self.syncPath_lineEdit)
        MainWindow.setTabOrder(self.syncPath_lineEdit, self.loadSyncPath_pushButton)
        MainWindow.setTabOrder(self.loadSyncPath_pushButton, self.useStimOrder_checkBox)
        MainWindow.setTabOrder(self.useStimOrder_checkBox, self.stimOrder_lineEdit)
        MainWindow.setTabOrder(self.stimOrder_lineEdit, self.loadStimOrderPath_pushButton)
        MainWindow.setTabOrder(self.loadStimOrderPath_pushButton, self.savePath_lineEdit)
        MainWindow.setTabOrder(self.savePath_lineEdit, self.setSavePath_pushButton)
        MainWindow.setTabOrder(self.setSavePath_pushButton, self.loadPreset_pushButton)
        MainWindow.setTabOrder(self.loadPreset_pushButton, self.savePreset_pushButton)
        MainWindow.setTabOrder(self.savePreset_pushButton, self.setDefaults_pushButton)
        MainWindow.setTabOrder(self.setDefaults_pushButton, self.numDiffStims_spinBox)
        MainWindow.setTabOrder(self.numDiffStims_spinBox, self.everyXStims_spinBox)
        MainWindow.setTabOrder(self.everyXStims_spinBox, self.startOnStim_spinBox)
        MainWindow.setTabOrder(self.startOnStim_spinBox, self.syncFrameChannel_lineEdit)
        MainWindow.setTabOrder(self.syncFrameChannel_lineEdit, self.syncStimChannel_lineEdit)
        MainWindow.setTabOrder(self.syncStimChannel_lineEdit, self.syncStartSec_doubleSpinBox)
        MainWindow.setTabOrder(self.syncStartSec_doubleSpinBox, self.syncStopSec_doubleSpinBox)
        MainWindow.setTabOrder(self.syncStopSec_doubleSpinBox, self.preSeconds_doubleSpinBox)
        MainWindow.setTabOrder(self.preSeconds_doubleSpinBox, self.postSeconds_doubleSpinBox)
        MainWindow.setTabOrder(self.postSeconds_doubleSpinBox, self.frameRate_doubleSpinBox)
        MainWindow.setTabOrder(self.frameRate_doubleSpinBox, self.averageImageStart_doubleSpinBox)
        MainWindow.setTabOrder(self.averageImageStart_doubleSpinBox, self.averageImageStop_doubleSpinBox)
        MainWindow.setTabOrder(self.averageImageStop_doubleSpinBox, self.methodRaw_checkBox)
        MainWindow.setTabOrder(self.methodRaw_checkBox, self.methodDF_checkBox)
        MainWindow.setTabOrder(self.methodDF_checkBox, self.methodDFF_checkBox)
        MainWindow.setTabOrder(self.methodDFF_checkBox, self.methodZscore_checkBox)
        MainWindow.setTabOrder(self.methodZscore_checkBox, self.makeColourImage_checkBox)
        MainWindow.setTabOrder(self.makeColourImage_checkBox, self.makeMaxImage_checkBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STA Movie Maker"))
        self.paths_groupBox.setTitle(_translate("MainWindow", "Paths"))
        self.loadSyncPath_pushButton.setText(_translate("MainWindow", "..."))
        self.loadStimOrderPath_pushButton.setText(_translate("MainWindow", "..."))
        self.useStimOrder_checkBox.setText(_translate("MainWindow", "Stim order"))
        self.setSavePath_pushButton.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Save path"))
        self.label_2.setText(_translate("MainWindow", "Sync file"))
        self.label.setText(_translate("MainWindow", "Movie"))
        self.loadMoviePath_pushButton.setText(_translate("MainWindow", "..."))
        self.presets_groupBox.setTitle(_translate("MainWindow", "Presets"))
        self.setDefaults_pushButton.setText(_translate("MainWindow", "Set defaults"))
        self.loadPreset_pushButton.setText(_translate("MainWindow", "Load preset"))
        self.savePreset_pushButton.setText(_translate("MainWindow", "Save preset"))
        self.loadedPreset_label.setText(_translate("MainWindow", "Loaded preset: (None)"))
        self.settings_groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox.setTitle(_translate("MainWindow", "Stim setup"))
        self.label_6.setText(_translate("MainWindow", "Different stims"))
        self.label_7.setText(_translate("MainWindow", "Every X stims"))
        self.label_14.setText(_translate("MainWindow", "Start on stim"))
        self.groupBox1.setTitle(_translate("MainWindow", "Sync file"))
        self.label_11.setText(_translate("MainWindow", "Frame channel"))
        self.label_12.setText(_translate("MainWindow", "Sync stop (s)"))
        self.label_13.setText(_translate("MainWindow", "Sync start (s)"))
        self.label_10.setText(_translate("MainWindow", "Stim channel"))
        self.groupBox2.setTitle(_translate("MainWindow", "Timing"))
        self.label_5.setText(_translate("MainWindow", "Frame rate (fps)"))
        self.label_4.setText(_translate("MainWindow", "Post (s)"))
        self.label_3.setText(_translate("MainWindow", "Pre (s)"))
        self.label_9.setText(_translate("MainWindow", "Z planes"))
        self.groupBox3.setTitle(_translate("MainWindow", "Average image"))
        self.label_16.setText(_translate("MainWindow", "Stop (s)"))
        self.averageImageStart_doubleSpinBox.setToolTip(_translate("MainWindow", "Post-stimulus onset"))
        self.label_15.setText(_translate("MainWindow", "Start (s)"))
        self.colourByTime_checkBox.setText(_translate("MainWindow", "Colour by time"))
        self.useSingleTrials_checkBox.setText(_translate("MainWindow", "Save single trial snapshots"))
        self.groupBox4.setTitle(_translate("MainWindow", "Methods"))
        self.methodRaw_checkBox.setText(_translate("MainWindow", "Raw"))
        self.methodDF_checkBox.setText(_translate("MainWindow", "∆F"))
        self.methodZscore_checkBox.setText(_translate("MainWindow", "Z-score"))
        self.methodDFF_checkBox.setText(_translate("MainWindow", "∆F/F"))
        self.gridGroupBox.setTitle(_translate("MainWindow", "Misc"))
        self.doThreshold_checkBox.setText(_translate("MainWindow", "Threshold"))
        self.threshold_doubleSpinBox.setToolTip(_translate("MainWindow", "Values less than this set to zero"))
        self.groupBox5.setTitle(_translate("MainWindow", "Combine multiple stims"))
        self.makeColourImage_checkBox.setText(_translate("MainWindow", "Make colour image"))
        self.makeMaxImage_checkBox.setText(_translate("MainWindow", "Make MAX image"))
        self.useCorrelationImage_checkBox.setText(_translate("MainWindow", "Use correlation image (V)"))
        self.blurHandS_checkBox.setText(_translate("MainWindow", "Blur H and S"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Motion correction"))
        self.doMotionCorrection_checkBox.setText(_translate("MainWindow", "Do motion correction?"))
        self.useCUDA_checkBox.setText(_translate("MainWindow", "Use CUDA?"))
        self.run_pushButton.setText(_translate("MainWindow", "Run"))
        self.openResultsDir_checkBox.setText(_translate("MainWindow", "Open results directory on completion"))

